version: '3.8'

services:
  web:
    build: ./docker_service_web
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/swa1
    volumes:
      - ./docker_service_web:/usr/src/app
    networks:
      - swa1_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/swa1.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
    networks:
      - swa1_net

  db:
    build: ./docker_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swa1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - swa1_net

volumes:
  postgres_data:
    driver: local

networks:
  swa1_net: